import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";
import sharp from "sharp";
import { MetadataCache } from "./metadata-cache.js";

/**
 * Thumbnail generator + batch backfiller.
 *
 * Covers downloaded by the scrapers live in `config/metadata/covers/<system>/`
 * as PNGs sized according to whatever the upstream source returned (often
 * 500–1024px). The grid renders cards up to ~292px wide and on HiDPI displays
 * the browser fetches 2x physical pixels, so thumbnails need to be ~600px
 * to stay sharp without bouncing back to the full PNG.
 *
 * Design choices:
 *  - 600px width covers the 292px-card × 2x-DPR worst case. Height auto-scaled
 *    to preserve aspect ratio (covers aren't always 3:4).
 *  - JPEG quality 90 with mozjpeg keeps file size in the 30–60 KB range while
 *    looking visually lossless against the PNG at grid resolution.
 *  - Idempotent: skip regeneration if the thumbnail is newer than the source.
 *    Scraper re-runs that rewrite the cover invalidate via mtime.
 *  - Versioned: bump THUMBNAIL_VERSION when output dimensions/quality change
 *    so existing libraries get their thumbnail dir wiped on the next launch
 *    (see migrateThumbnailVersion). Otherwise users would keep their old
 *    low-res thumbnails forever because the mtime check skips regeneration.
 */

export const THUMBNAIL_WIDTH = 600;
export const THUMBNAIL_QUALITY = 90;

/**
 * Bumped from 1 to 2 in v0.1.4 when we doubled thumbnail width to fix the
 * blurry-grid bug. Bump again whenever output specs change so existing
 * libraries auto-regenerate on next launch.
 */
export const THUMBNAIL_VERSION = 2;
const VERSION_MARKER_FILE = ".version";

/**
 * Generate a thumbnail for a given cover, if one is missing or stale. Safe to
 * call synchronously after writing the cover file — sharp resolves the promise
 * once the thumbnail is on disk. Errors are swallowed and logged; a missing
 * thumbnail just means the UI falls back to the full cover (slower but
 * correct), which is strictly better than crashing the scraper.
 */
export async function ensureThumbnail(
  coverPath: string,
  thumbnailPath: string
): Promise<void> {
  try {
    if (!existsSync(coverPath)) return;

    if (existsSync(thumbnailPath)) {
      const coverMtime = statSync(coverPath).mtimeMs;
      const thumbMtime = statSync(thumbnailPath).mtimeMs;
      if (thumbMtime >= coverMtime) return; // up to date
    }

    mkdirSync(path.dirname(thumbnailPath), { recursive: true });
    await sharp(coverPath)
      .resize(THUMBNAIL_WIDTH, null, { withoutEnlargement: true })
      .jpeg({ quality: THUMBNAIL_QUALITY, mozjpeg: true })
      .toFile(thumbnailPath);
  } catch (err) {
    console.warn(`[thumbnail] Failed to generate ${thumbnailPath}:`, err);
  }
}

/**
 * Walk every cover in the cache and regenerate missing/stale thumbnails.
 * Used by the renderer's "rebuild thumbnails" Settings action and by a
 * first-run pass so users upgrading from pre-thumbnail builds get fast
 * grids without having to re-scrape.
 *
 * Returns the counts so the UI can show progress: { generated, skipped,
 * failed }. Iteration is sequential because sharp uses libvips internally
 * and is already multi-threaded per call — parallelising in JS just
 * increases memory pressure without throughput gains.
 */
export async function backfillThumbnails(
  cache: MetadataCache
): Promise<{ generated: number; skipped: number; failed: number }> {
  let generated = 0;
  let skipped = 0;
  let failed = 0;

  const coversRoot = path.resolve(cache.getThumbnailsDir(), "..", "covers");
  if (!existsSync(coversRoot)) return { generated, skipped, failed };

  const systems = readdirSync(coversRoot, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name);

  for (const systemId of systems) {
    const systemDir = path.resolve(coversRoot, systemId);
    const files = readdirSync(systemDir).filter((f) =>
      /\.(png|jpe?g|webp)$/i.test(f)
    );
    for (const file of files) {
      const coverPath = path.resolve(systemDir, file);
      const baseName = file.replace(/\.[^.]+$/, "");
      const thumbPath = cache.getThumbnailPath(systemId, baseName);

      try {
        if (existsSync(thumbPath)) {
          const coverMtime = statSync(coverPath).mtimeMs;
          const thumbMtime = statSync(thumbPath).mtimeMs;
          if (thumbMtime >= coverMtime) {
            skipped++;
            continue;
          }
        }
        await ensureThumbnail(coverPath, thumbPath);
        generated++;
      } catch {
        failed++;
      }
    }
  }

  return { generated, skipped, failed };
}

/**
 * Wipe the thumbnails directory if it was generated by a previous version
 * of this module (different width/quality/format). Call once on app
 * startup; lazily-regenerated thumbs from `ensureThumbnail` will refill
 * the directory on demand. Idempotent — no-op when the marker matches.
 *
 * The marker lives at `<thumbnails>/.version` as plain text. Missing
 * marker on a non-empty dir is treated as "legacy / unknown version" and
 * triggers a wipe; missing marker on a clean dir just writes one.
 */
export function migrateThumbnailVersion(thumbnailsDir: string): void {
  try {
    const markerPath = path.join(thumbnailsDir, VERSION_MARKER_FILE);
    let existing: number | null = null;
    if (existsSync(markerPath)) {
      try {
        existing = parseInt(readFileSync(markerPath, "utf-8").trim(), 10);
        if (Number.isNaN(existing)) existing = null;
      } catch {
        existing = null;
      }
    }
    if (existing === THUMBNAIL_VERSION) return;

    if (existsSync(thumbnailsDir)) {
      // Wipe everything (per-system subdirs + stale marker) so the next
      // ensureThumbnail call regenerates at the new spec.
      rmSync(thumbnailsDir, { recursive: true, force: true });
    }
    mkdirSync(thumbnailsDir, { recursive: true });
    writeFileSync(markerPath, String(THUMBNAIL_VERSION), "utf-8");
  } catch (err) {
    console.warn("[thumbnail] migrateThumbnailVersion failed:", err);
  }
}
